### PR TITLE
Load ads in background by default

### PR DESCRIPTION
**Pull request by raxxpack**
The issue is mopub loads ads on the main thread, so the network callbacks are blocked while scrolling which results in ads not showing. It displays as soon as the user lifts their finger, however this is often too late and we don't get the impression since they have scrolled past by this point.

### CODE REVIEW

**Comment by daftdavy** [comment]
@raxxpack the code itself looks fine, but I'm wondering is the motivation for the change? Aren't we having issues with ads loading in the background atm?

**Comment by raxxpack** [comment]
To clarify, Mopub did their ad loading on the main thread which was causing ads not display if the user is scrolling in home.

**Comment by raxxpack** [comment]
These are only for native ads by the way, and it will still use their default handling when the app is backgrounded during load.

**Comment by daftdavy** [comment]
:shipit: but please add a Changelog for this. If we notice changes in tracking of impressions or clicks, it'll be important to be able to track it down to this update.

**Pull request merged**
